name:                MarkovGenerator
version:             0.1.0.0
github:              "GJHap/MarkovGenerator"
license:             BSD3
author:              "Gregory Hapgood"
maintainer:          "greghap@gmail.com"
copyright:           "2020 Gregory Hapgood"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/GJHap/MarkovGenerator#readme>

dependencies:
- base >= 4.7 && < 5
- mtl == 2.2.2
- containers == 0.6.2.1
- random == 1.1

library:
  source-dirs: src

executables:
  MarkovGenerator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MarkovGenerator
